### ISSUE TITLE
Create an item in a shopcart

### ISSUE THREAD

**Issue by JiaxiXie** [CSCI-GA-2820-SU24-001/shopcarts#2]
**As a** customer
**I need** to add an item to my shopcart
**So that** I can select products to purchase

### Details and Assumptions

* The request contains the id associated with the shopcart to which the item is to be added, and details of the item to be added (product_id, name, quantity, price)
* Shopcart with the given id exists

### Acceptance Criteria

```gherkin
Given a customer with an existing shopcart
When a POST request to add an item to the shopcart is made via /shopcarts/{id}/items
Then the item should be added to the shopcart in the database
And the total price of items in the shopcart should be updated in the database
And the updated shopcart details should be returned in JSON along with a 201 status
```

**Comment by JiaxiXie** [comment]
As a shopping manager
I need to create a item
So that a new item is created when added to the shopping cart

Details and Assumptions
Determine the name, number of items, price for the item to be stored in the database

Acceptance Criteria
Given database and service are running
When an item is created
Then the shopping cart should be updated with the new item in it

**Comment by JiaxiXie** [comment]
As a shopping manager
I need to create a item
So that a new item is created when added to the shopping cart

Details and Assumptions
Determine the name, number of items, price for the item to be stored in the database

Acceptance Criteria
Given database and service are running
When an item is created
Then the shopping cart should be updated with the new item in it

**Comment by manisha-goyal** [comment]
Suggesting the following edits:

As a customer
I need to add an item to my shopcart
So that I can select products to purchase

Details and Assumptions

- Each item added will reference a product id

Acceptance Criteria
Given a customer with an existing shopcart
When a POST request to add an item to the shopcart is made via /shopcarts/{id}/items
Then the item should be added to the shopcart in the database, and the updated shopcart details should be returned in JSON

**Comment by JiaxiXie** [comment]
As the professor mentioned in Slack, I think we should change the issue as "Create an item in the shopcart"

**Comment by manisha-goyal** [comment]
Yes makes sense

**Comment by JiaxiXie** [comment]
Also, maybe the post request should be /shopcarts/{id}/items/{id} ?

**Comment by manisha-goyal** [comment]
Since the item_id is system generated, we will not need to take it in the request.
