### ISSUE TITLE
Create a shopcart

### ISSUE THREAD

**Issue by JiaxiXie** [CSCI-GA-2820-SU24-001/shopcarts#3]
**As a** new customer
**I need** to create a new shopcart
**So that** I can start adding products I want to purchase

 ### Details and Assumptions

* The request contains the customer id associated with the shopcart to be created
* Each customer can have only one shopcart
* A shopping cart associated with the customer does not exist
* The shopcart will be empty when created, and total price will be 0

 ### Acceptance Criteria

```gherkin
Given a customer without an existing shopcart
When a POST request to create a shopcart is made via /shopcarts
Then a new shopcart should be created in the database
And returned with a 201 status and the shopcart details in JSON
```

**Comment by manisha-goyal** [comment]
Suggesting the following edits:

As a new customer
I need to create a new shopcart
So that I can start adding products I want to purchase

Acceptence Criteria:
 Given a customer without an existing shopcart
 When a request to create a shopcart is made via /shopcarts/{id} 
 Then a new shopcart should be created and returned with a 201 status and the shopcart details in JSON

**Comment by RogerHuangPKX** [comment]
I want to add a little more details about it. It should be automatically generated once the user is registered. 🤔

**Comment by manisha-goyal** [comment]
@RogerHuangPKX From my understanding, new users will register via the /customers API. For /shopcarts/{id}, we only need to create new shopcarts if they don't already exist. What do you think?

**Comment by RogerHuangPKX** [comment]
@manisha-goyal Sure. But it’s more like a hook. When a new user registers, several services and API should be called (creating user profile/ assign user id / creating shopping cart/ assign shopping cart id/ bind user id and cart id etc). But you are right. We should only focus how to create. I’m so sorry I think too much. 🥲

**Comment by manisha-goyal** [comment]
@RogerHuangPKX I get what you mean, the web hook part makes sense!
