### ISSUE TITLE
Add GitHub Actions CI badge to README

### ISSUE THREAD

**Issue by manisha-goyal** [CSCI-GA-2820-SU24-001/shopcarts#44]
**As a** developer
**I need** to add a CI badge to the README file
**So that** everyone can see the current build status of the project
   
 ### Details and Assumptions
 * The badge will be added to the README.md file
 * The badge will display the build status (e.g., passing or failing) 
 * The shopcarts service is hosted on Git
 * The GitHub Actions workflow for running unit tests and checking code quality has been set up
 * The GitHub Actions CI badge URL is available
   
 ### Acceptance Criteria  
   
 ```gherkin
Given a shopcarts service repository with a GitHub Actions CI workflow
When the workflow is running
Then the README.md file should display a badge showing the current build status
```

**Comment by RogerHuangPKX** [comment]
<img width="1314" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMksrQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bf9845cfab08f11fc86a89de99639625ff781a52/image.png" alt="image.png" />

We can customize our own badges and add a few highlight here.  Please refer this image.
