### ISSUE TITLE
Update an item in a shopcart

### ISSUE THREAD

**Issue by RogerHuangPKX** [CSCI-GA-2820-SU24-001/shopcarts#7]
**As a** customer
**I need** update the quantity of an item in my shopping cart
**So that** I can change the quantity of a product I want to purchase
   
 ### Details and Assumptions
 * Only product quantities can be updated
 * The request contains the id associated with the shopcart, the id of the item to be updated, and the new quantity of the item
 * Shopcart with the given id exists and contains the item with given id
   
 ### Acceptance Criteria  
   
 ```gherkin
Given a customer with an existing shopcart and shopcart item
When a PUT request to update the item is made via /shopcarts/{id}/items/{item_id}
Then the item should be updated in the database with the new quantity
And the total price of items in the shopcart should be updated in the database
And the updated details should be returned in JSON along with a 200 status
```

**Comment by manisha-goyal** [comment]
Suggesting the following edits:

Acceptance Criteria
Given a customer with an existing shopcart
When a PUT request to update the item is made via /shopcarts/{id}/items/{item_id}
Then the item should be updated in the database with the new quantity and the updated details should be returned in JSON
